stages:
  - build
  - test
  - deploy

build-dev:
  when: manual
  stage: build
  #image: node:16.18.1-slim
  tags:
    - frontend
    - dev
  script:
    - echo "Building UI"
    - yarn install
    - yarn run build:prod
  #artifacts:
    
test-dev:
  when: manual
  stage: test
  #image: node:16.18.1-slim
  tags:
    - frontend
    - dev
  script:
    - echo "Testing UI..."
    - id
    - echo $PATH
    - yarn install
    - yarn run test
    #- cd /opt/ospr/frontend-src/ui-7.1/
  allow_failure: true

deploy-dev:
  when: manual
  stage: deploy
  only:
    - develop
  tags:
    - frontend
    - dev
  script:
    - echo "Deploying to dev-ospr.g.ent.cloud-nuage.canada.ca ..."