stages:
  - build
  - test
  - deploy

build-dev:
  stage: build
  #image: node:16.18.1-slim
  tags:
    - frontend
    - dev
  script:
    - echo "Building UI"
    - id
    - echo $PATH
    - cd /opt/ospr/frontend-src/ui-7.1/
    - yarn install
    - yarn run build:prod

test-dev:
  stage: test
  #image: node:16.18.1-slim
  tags:
    - frontend
    - dev
  script:
    - echo "Testing UI..."
    - id
    - echo $PATH
    - cd /opt/ospr/frontend-src/ui-7.1/
    - yarn install
    - yarn run test
  allow_failure: true
  only: 
    - branches

deploy-dev:
  when: manual
  stage: deploy
  tags:
    - frontend
    - dev
  script:
    - echo "Deploying to dev-ospr.g.ent.cloud-nuage.canada.ca ..."