stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:16.18.1-slim
  tags:
    - frontend
    - dev
  script:
    - echo "Building UI"
    - yarn install
    - yarn run build:prod

test:
  stage: test
  image: node:16.18.1-slim
  tags:
    - frontend
    - dev
  script:
    - echo "Testing UI..."
    - yarn install
    - yarn run test

deploy-dev:
  stage: deploy
  tags:
    - frontend
    - dev
  script:
    - echo "Deploying to dev-ospr.g.ent.cloud-nuage.canada.ca ..."