# This image will be published as dspace/dspace-angular
# See https://github.com/DSpace/dspace-angular/tree/main/docker for usage details

FROM node:14-alpine as build_aus

WORKDIR /app
ADD . /app/

# We run yarn install with an increased network timeout (5min) to avoid "ESOCKETTIMEDOUT" errors from hub.docker.com
# See, for example https://github.com/yarnpkg/yarn/issues/5540
RUN yarn install --network-timeout 300000
# Set this to control the environmental config used
#ENV NODE_ENV apption
RUN yarn run set-env --apption
# Set again to control the type of build to be performed
ENV NODE_ENV development
RUN yarn run build:prod

# Use second image to serve output
# Use official nginx image as the base image
# Stage 2: Run the server
FROM node:14

WORKDIR /app

# Copy the built files from the previous stage
COPY --from=build_aus /app/dist /app/dist

# Install only production dependencies
COPY package*.json ./
#RUN npm install --only=production
RUN npm install

# Expose the port the app runs on
EXPOSE 4000

# Start the Angular Universal server
CMD ["node", "dist/server"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
