# The build and deploy steps for the OIR Project

variables:
  # Container registry service connection established during pipeline creation
  acrName: $(CONTAINER_REGISTRY_NAME)
  acrLoginServer: $(CONTAINER_REGISTRY_URL)
  serviceConnection: $(DOCKER_REG_SERVICE_CONNECTION)
  azureSubscription: $(DOCKER_REG_SERVICE_CONNECTION)
  azureSubscription2: $(AZURE_SUBSCRIPTION)
  imageNameServer: $(IMAGE_REPOSITORY_AUS)
  imageNameNginx: $(IMAGE_REPOSITORY_NGINX)
  dockerfilePath: '$(Build.SourcesDirectory)'
  dockerfileName: '$(DOCKERFILE_NAME)'
  tag: '$(Build.BuildId)'
  appServiceName: $(APP_SERVICE_NAME)
  resourceGroup: $(RESOURCE_GROUP)

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push Docker Images
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Set the ACR login server
          az acr login --name $(acrName)

          # Build the Docker images
          docker build -t $(acrLoginServer)/$(imageNameServer):$(Build.BuildId) -f Dockerfile_aus-apption .
          docker build -t $(acrLoginServer)/$(imageNameNginx):$(Build.BuildId) -f Dockerfile_nginx-apption .

          # Push the Docker images to ACR
          docker push $(acrLoginServer)/$(imageNameServer):$(Build.BuildId)
          docker push $(acrLoginServer)/$(imageNameNginx):$(Build.BuildId)

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Set the ACR login server
          az acr login --name $(acrName)

          # Generate the Docker Compose file dynamically
          echo "version: '3'
          services:
            angular_universal_server:
              image: $(acrLoginServer)/$(imageNameServer):$(Build.BuildId)
              ports:
                - '4000:4000'
            nginx:
              image: $(acrLoginServer)/$(imageNameNginx):$(Build.BuildId)
              ports:
                - '80:80'
              depends_on:
                - angular_universal_server" > docker-compose.yml

          # Deploy to Azure App Service
          az webapp config container set --name $(appServiceName) --resource-group $(resourceGroup) --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml

