# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- oir-sandbox
- oir-7.3-sandbox

resources:
- repo: self

extends:
  template: azure-pipeline.yml
