# The build and deploy steps for the OIR Project

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: $(DOCKER_REG_SERVICE_CONNECTION)
  imageRepository: $(IMAGE_REPOSITORY)
  containerRegistry: $(CONTAINER_REGISTRY)
  dockerfilePath: '$(Build.SourcesDirectory)'
  dockerfileName: '$(DOCKERFILE_NAME)'
  tag: '$(Build.BuildId)'
  azureSubscription: $(AZURE_SUBSCRIPTION)
  appName: $(APP_NAME)
  acrPassword: '$(ACR_PASSWORD)'
  resourceGroup: '$(RESOURCE_GROUP)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: Docker@2
      displayName: Build
      inputs:
        command: 'build'
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        Dockerfile: $(dockerfilePath)/$(dockerfileName)
        tags: $(tag)

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

    - task: AzureCLI@2
      displayName: 'Deploy container to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp config container set \
            --resource-group $(resourceGroup) \
            --name $(appName) \
            --container-image-name $(containerRegistry).azurecr.io/$(imageRepository):$(tag) \
            --container-registry-url https://$(containerRegistry).azurecr.io \
            --container-registry-user $(containerRegistry) \
            --container-registry-password $(acrPassword)
        failOnStandardError: false