# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- ostr-prod

resources:
- repo: self

extends:
  template: azure-pipeline.yml
